;Visual Basic 6 Runtime Library Telepítõ

Name "VB6 Runtime Komponensek"
CAption "Visual Basic 6 Runtime komponensek telepítése"


Subcaption 0 " "
Subcaption 1 " "
Subcaption 2 " "
Subcaption 3 " "
Subcaption 4 " "

MiscButtontext "<Vissza" "Következõ >" "Mégse" "Bezár"
Installbuttontext "Telepítés"

Outfile "vb6r.exe"
Dirshow hide
Installdir $SYSDIR

Licensetext "Kérem figyelmesen olvassa el az alábbi license feltételeket."
licensedata "license.txt"

